openapi: 3.0.0
info:
  title: API de Carrito
  version: 1.0.0
paths:
  /api/cart:
    get:
      summary: Obtiene todos los datos del carrito.
      tags:
        - Carrito
      responses:
        '200':
          description: Respuesta exitosa! Se retorna un arreglo con los datos del carrito.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '400':
          description: Se envió un dato no válido.
        '500':
          description: Error inesperado en el servidor, no se pudo manejar el proceso.

  /api/cart/{_id}:
    get:
      summary: Obtiene los datos de un carrito buscando por _id.
      tags:
        - Carrito
      parameters:
        - name: _id
          in: path
          required: true
          description: Id del carrito que se desea solicitar.
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa! Se retorna un carrito.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '400':
          description: Se envió un dato no válido.
        '500':
          description: Error inesperado en el servidor, no se pudo manejar el proceso.
          
  /api/cart/increase/{CId}/product/{PId}/{quantity}:
    post:
      summary: Añade un producto al carrito.
      tags:
        - Carrito
      parameters:
        - name: CId
          in: path
          required: true
          description: Id del carrito al que se desea añadir el producto.
          schema:
            type: string
        - name: PId
          in: path
          required: true
          description: Id del producto que se desea añadir al carrito.
          schema:
            type: string
        - name: quantity
          in: path
          required: true
          description: Cantidad del producto que se desea añadir al carrito.
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Producto añadido exitosamente al carrito.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '400':
          description: Datos de producto no válidos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Invalid product data
        '404':
          description: Carrito o producto no encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Cart or product not found
        '409':
          description: Stock insuficiente del producto.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Insufficient stock

    /api/cart/increase/{CId}/product/{PId}/{quantity}:
    put:
      summary: Aumenta la cantidad de un producto en el carrito y resta el stock del producto.
      tags:
        - Carrito
      parameters:
        - name: CId
          in: path
          required: true
          description: Id del carrito al que se desea aumentar la cantidad del producto.
          schema:
            type: string
        - name: PId
          in: path
          required: true
          description: Id del producto al que se desea aumentar la cantidad en el carrito.
          schema:
            type: string
        - name: quantity
          in: path
          required: true
          description: Cantidad que se desea aumentar al producto en el carrito.
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Cantidad del producto en el carrito aumentada exitosamente y stock del producto restado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '400':
          description: Datos no válidos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Invalid data
        '404':
          description: Carrito o producto no encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Cart or product not found
        '409':
          description: Stock insuficiente del producto.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Insufficient stock

  /api/cart/decrease/{CId}/product/{PId}/{quantity}:
    put:
      summary: Disminuye la cantidad de un producto en el carrito y aumenta el stock del producto.
      tags:
        - Carrito
      parameters:
        - name: CId
          in: path
          required: true
          description: Id del carrito al que se desea disminuir la cantidad del producto.
          schema:
            type: string
        - name: PId
          in: path
          required: true
          description: Id del producto al que se desea disminuir la cantidad en el carrito.
          schema:
            type: string
        - name: quantity
          in: path
          required: true
          description: Cantidad que se desea disminuir al producto en el carrito.
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Cantidad del producto en el carrito disminuida exitosamente y stock del producto aumentado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '400':
          description: Datos no válidos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Invalid data
        '404':
          description: Carrito o producto no encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Cart or product not found


  /api/cart/delete/{CId}/product/{PId}:
    delete:
      summary: Elimina un producto del carrito.
      tags:
        - Carrito
      parameters:
        - name: CId
          in: path
          required: true
          description: Id del carrito del que se desea eliminar el producto.
          schema:
            type: string
        - name: PId
          in: path
          required: true
          description: Id del producto que se desea eliminar del carrito.
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado exitosamente del carrito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '404':
          description: Carrito o producto no encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Cart or product not found

  /api/cart/delete/{CId}:
    delete:
      summary: Elimina un carrito.
      tags:
        - Carrito
      parameters:
        - name: CId
          in: path
          required: true
          description: Id del carrito que se desea eliminar.
          schema:
            type: string
      responses:
        '200':
          description: Carrito eliminado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '404':
          description: Carrito no encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Carrito no encontrado

  /api/cart/finalizePurchase:
    post:
      summary: Finaliza una compra.
      tags:
        - Carrito
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
      responses:
        '200':
          description: Compra finalizada exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  purchaseId:
                    type: string
        '401':
          description: Usuario no autorizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Unauthorized

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: Id del carrito.
        products:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
                description: Id del producto en el carrito.
              product:
                type: string
                description: Id del producto.
              title:
                type: string
                description: Título del producto.
              price:
                type: number
                description: Precio del producto.
              thumbnail:
                type: string
                description: Miniatura del producto.
              quantity:
                type: integer
                description: Cantidad del producto en el carrito.
