export const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    VALIDATION_ERROR: 4, 
    NOT_FOUND: 5, 
    SERVER_ERROR: 6,
    EMAIL_ERROR: 7,
    UNAUTHORIZED: 8,
    VIEW_INTERNAL_SERVER_ERROR: 9,
};